version: "3"
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=garkgodwin
      - MONGO_INITDB_ROOT_PASSWORD=uSpaxLTlS7dluaAA
    volumes:
      - type: bind
        source: ./data
        target: /data/db
